### ISSUE TITLE
sendMultiSig problem

### ISSUE THREAD

**Issue by Wangmmx** [BitGo/eth-multisig-v2#14]
I have deployed the contract on Kovan. But I'm having trouble transferring Eth using SendMultiSig. I don't know if I got the correct data and signature. Can you please help me?
![image](https://user-images.githubusercontent.com/22836587/52853954-0c9cda80-3158-11e9-85ab-82ff2e993b78.png)

**Comment by jagonzalez11** [comment]
There's no ecrecover function in the contract to handle the `return ecrecover(operationHash, v, r, s)` that is called by recoverAddressFromSignature

**Comment by Wangmmx** [comment]
I figured out, thanks anyway

**Comment by affankhan43** [comment]
can guide me how can i get data and signature

**Comment by todipratik** [comment]
Hey @Wangmmx, How did you compute `keccak256` required for `signature` field of `sendMultiSig`?

**Comment by Poonam911** [comment]
Hii @Wangmmx 

can you guide me how to execute the  SendMultiSig function beacsue i got revert transaction error again and again 
thanks & regards 
Poonam Singh
